//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSkyMartSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheskymartEntities : DbContext
    {
        public TheskymartEntities()
            : base("name=TheskymartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country_master> Country_master { get; set; }
        public virtual DbSet<Division_master> Division_master { get; set; }
        public virtual DbSet<Group_master> Group_master { get; set; }
        public virtual DbSet<Item_Details> Item_Details { get; set; }
        public virtual DbSet<Item_master> Item_master { get; set; }
        public virtual DbSet<Location_master> Location_master { get; set; }
        public virtual DbSet<Price_master> Price_master { get; set; }
        public virtual DbSet<Sub_Group_master> Sub_Group_master { get; set; }
        public virtual DbSet<Supplier_Masters> Supplier_Masters { get; set; }
        public virtual DbSet<Category_Master> Category_Master { get; set; }
        public virtual DbSet<V_Home_Page> V_Home_Page { get; set; }
    }
}
