//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSkyMartSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_master()
        {
            this.Item_Details = new HashSet<Item_Details>();
            this.Price_master = new HashSet<Price_master>();
        }
    
        public long Item_Code { get; set; }
        public string Item_Name { get; set; }
        public string Item_Brand { get; set; }
        public string Item_Description { get; set; }
        public int Item_Division { get; set; }
        public int Item_Group { get; set; }
        public int Item_Sub_Group { get; set; }
    
        public virtual Division_master Division_master { get; set; }
        public virtual Group_master Group_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Details> Item_Details { get; set; }
        public virtual Sub_Group_master Sub_Group_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_master> Price_master { get; set; }
    }
}
