//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSkyMartSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location_master()
        {
            this.Supplier_Masters = new HashSet<Supplier_Masters>();
        }
    
        public int Location_ID { get; set; }
        public string Location_Name { get; set; }
        public string Location_Currency { get; set; }
        public Nullable<double> Location_Currency_value { get; set; }
        public int Country_ID { get; set; }
    
        public virtual Country_master Country_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Masters> Supplier_Masters { get; set; }
    }
}
