//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSkyMartSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_master
    {
        public long Item_code { get; set; }
        public int Supplier_ID { get; set; }
        public Nullable<double> Supplier_Price { get; set; }
    
        public virtual Item_master Item_master { get; set; }
        public virtual Supplier_Masters Supplier_Masters { get; set; }
    }
}
