//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSkyMartSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Group_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sub_Group_master()
        {
            this.Item_master = new HashSet<Item_master>();
        }
    
        public int Sub_Group_ID { get; set; }
        public string Sub_Group_Name { get; set; }
        public int Group_ID { get; set; }
    
        public virtual Group_master Group_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_master> Item_master { get; set; }
    }
}
