//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSkyMartSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Home_Page
    {
        public long Item_Code { get; set; }
        public string Item_Name { get; set; }
        public string Item_Brand { get; set; }
        public string Division_Name { get; set; }
        public string Group_Name { get; set; }
        public string Sub_Group_Name { get; set; }
        public Nullable<double> Supplier_Price { get; set; }
        public int Supplier_ID { get; set; }
        public string Supplier_name { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email_id { get; set; }
        public Nullable<double> Credit_limit { get; set; }
        public Nullable<int> Payment_term { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Active_status { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public int Category_ID { get; set; }
        public string Logo_image { get; set; }
        public string Slide_1 { get; set; }
        public string Slide_2 { get; set; }
        public string Slide_3 { get; set; }
        public string Slide_4 { get; set; }
        public string Slide_5 { get; set; }
        public long Sno { get; set; }
        public long Expr1 { get; set; }
        public string Item_main_image { get; set; }
        public string Item_image_1 { get; set; }
        public string Item_image_2 { get; set; }
        public string Item_image_3 { get; set; }
        public string Item_image_4 { get; set; }
        public string Item_image_5 { get; set; }
    }
}
